fix: Fix clang ast can not find the std headers in some systems (#47)
In some systems, if the llvm path spefic to the `PATH` environment
variables, the clang AST will run with error that can not find the std
headers, e.g.,
`/opt/homebrew/opt/llvm@15/include/c++/v1/stdio.h:107:15: fatal error:
'stdio.h' file not found`.
So we filter the llvm path from the `PATH` to run the clang AST, it's a
little tricky but for a workaround.